# Generated by Django 5.0 on 2023-12-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_recipe_recipe_desciption'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Img',
            field=models.ImageField(default='abc', upload_to='Img'),
        ),
    ]
