# Generated by Django 5.0 on 2023-12-14 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recipe_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Img',
        ),
    ]
