# Generated by Django 5.0 on 2023-12-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_recipe_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='Recipe_Img',
            field=models.ImageField(default='null', upload_to=None),
        ),
    ]
