# Generated by Django 5.0 on 2023-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_recipe_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_Img',
            field=models.ImageField(default='null', upload_to='./'),
        ),
    ]
